version: "3.9"
services:
  devops:
    container_name: springboot
    image: "karimtrabelsi/devops-application:1.0.0"
    build: .
    ports:
      - "8087:8087"
    depends_on:
      - db-mysql

  db-mysql:
    image: "mysql:5.6"
    hostname: db-mysql
    container_name: db-mysqll
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
