version: "3.9"
services:
  backend:
    container_name: devops
    image: "therealmkadmi42/backend-java-app:1.0.0"
    build: .
    ports:
      - "8087:8087"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/university?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: "mysql:5.6"
    hostname: mysql
    container_name: mysql-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  angular-app:
    container_name: angular-app
    image: "therealmkadmi42/angular-app:1.0.0"
    build:
      context: ../frontend
    ports:
      - "4200:4200"
    command: [ "npm", "start", "--", "--host", "0.0.0.0" ]