version: "3.9"

services:
  candidats:
    container_name: candidats
    hostname: candidats
    image: "khalilturki/devops-application:1.0.0"  # Update with your Docker image name and tag
    ports:
      - "9000:8080"  # Map the container's port 8080 to host port 9000
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/your_database_name?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - eureka-server
      - db-mysql

  eureka-server:
    image: "your-eureka-server-image:tag"  # Update with your Eureka server image and tag
    container_name: eureka-server
    ports:
      - "8761:8761"

  db-mysql:
    image: "mysql:8.0"  # Update with the MySQL version you are using
    hostname: db-mysql
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=your_database_name
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
