version: "3.9"
services:
  backend:
    container_name: devops
    image: "therealmkadmi42/backend-java-app:1.0.0"
    build: .
    ports:
      - "8087:8087"
    environment:
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/university?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db-mysql

  mysql:
    image: "mysql:5.6"
    hostname: db-mysql
    container_name: db-mysqll
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
